[package]
name = "libtest-mimic"
version = "0.2.0"
authors = ["Lukas Kalbertodt <lukas.kalbertodt@gmail.com>"]

description = """
Write your own test harness that looks and behaves like the built-in test \
harness used by `rustc --test`
"""
documentation = "https://docs.rs/libtest-mimic"
repository = "https://github.com/LukasKalbertodt/libtest-mimic"
license = "MIT/Apache-2.0"
keywords = ["libtest", "test", "built-in", "framework"]
categories = ["development-tools::testing", "development-tools::build-utils"]
readme = "README.md"


[dependencies]
structopt = "0.3.2"
termcolor = "1.0.5"
